#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$HARMONY_HOME/native/build/cmake/ohos.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DOHOS_ARCH="arm64-v8a" \
-DOHOS_STL=c++_static \
-DMNN_USE_LOGCAT=true \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DOHOS_PLATFORM_LEVEL=20  \
-DMNN_BUILD_LLM=ON \
-DMNN_BUILD_LLM_OMNI=ON \
-DMNN_SEP_BUILD=OFF \
-DHIAI_VERBOSE=ON \
-DHIAI_INT8_DIAG=0 \
-DMNN_HIAI_CACHE_OM_BY_CHUNK=OFF \
-DMNN_HIAI_FREE_CONST_HOST=1 \
-DMNN_LOW_MEMORY=ON \
-DMNN_SUPPORT_TRANSFORMER_FUSE=ON \
-DMNN_BUILD_SHARED_LIBS=ON \
-DMOBIINFER_MNN=OFF \
-DMNN_NPU:BOOL=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j64
